In [8]:
import numpy as np

## NumPy Array Indexing

In [9]:
# Create an array for indexing with 89 as the first element
arr_index = np.array([89, 2, 7, 12, 17, 22])
print("Original array for indexing:", arr_index)

# Accessing elements by index
print("First element (index 0):", arr_index[0])
print("Third element (index 2):", arr_index[2])

# Accessing elements using negative indexing
print("Last element (negative index -1):", arr_index[-1])

Original array for indexing: [89  2  7 12 17 22]
First element (index 0): 89
Third element (index 2): 7
Last element (negative index -1): 22


## NumPy Array Slicing

In [10]:
# Create an array for slicing with 89 as the first element
arr_slice = np.array([89, 11, 22, 33, 44, 55, 66, 77])
print("Original array for slicing:", arr_slice)

# Basic slicing (elements from index 1 to 4, exclusive of 5)
print("Slice from index 1 to 5 (exclusive):", arr_slice[1:5])

# Slicing from the beginning to index 3
print("Slice from start to index 3 (exclusive):", arr_slice[:3])

# Slicing from index 4 to the end
print("Slice from index 4 to end:", arr_slice[4:])

# Slicing with a step (every second element)
print("Slice with step 2:", arr_slice[::2])

Original array for slicing: [89 11 22 33 44 55 66 77]
Slice from index 1 to 5 (exclusive): [11 22 33 44]
Slice from start to index 3 (exclusive): [89 11 22]
Slice from index 4 to end: [44 55 66 77]
Slice with step 2: [89 22 44 66]


## NumPy Array Reshaping

In [11]:
# Create a 1D array for reshaping with 89 as the first element
arr_reshape = np.array([89, 10, 20, 30, 40, 50])
print("Original 1D array for reshaping:", arr_reshape)

# Reshape to a 2D array (2 rows, 3 columns)
arr_2d = arr_reshape.reshape(2, 3)
print("\nReshaped 2D array (2x3):\n", arr_2d)

# Reshape to a 3D array (2x3x1)
arr_3d = arr_reshape.reshape(2, 3, 1)
print("\nReshaped 3D array (2x3x1):\n", arr_3d)

Original 1D array for reshaping: [89 10 20 30 40 50]

Reshaped 2D array (2x3):
 [[89 10 20]
 [30 40 50]]

Reshaped 3D array (2x3x1):
 [[[89]
  [10]
  [20]]

 [[30]
  [40]
  [50]]]


## NumPy Array Joining

In [12]:
# Create two arrays for joining, both starting with 89
arr_join1 = np.array([89, 1, 2])
arr_join2 = np.array([89, 3, 4]) # First element of second array also 89 as per instruction.
print("Array 1 for joining:", arr_join1)
print("Array 2 for joining:", arr_join2)

# Join arrays along axis 0 (row-wise for 1D arrays)
joined_arr = np.concatenate((arr_join1, arr_join2))
print("\nJoined array:", joined_arr)

# Example with 2D arrays
arr_join3 = np.array([[89, 1], [2, 3]])
arr_join4 = np.array([[4, 5], [6, 7]])
print("\nArray 3 (2D) for joining:\n", arr_join3)
print("Array 4 (2D) for joining:\n", arr_join4)

# Join 2D arrays vertically (vstack)
joined_vstack = np.vstack((arr_join3, arr_join4))
print("\nVertically stacked (vstack):\n", joined_vstack)

# Join 2D arrays horizontally (hstack)
joined_hstack = np.hstack((arr_join3, arr_join4))
print("\nHorizontally stacked (hstack):\n", joined_hstack)

Array 1 for joining: [89  1  2]
Array 2 for joining: [89  3  4]

Joined array: [89  1  2 89  3  4]

Array 3 (2D) for joining:
 [[89  1]
 [ 2  3]]
Array 4 (2D) for joining:
 [[4 5]
 [6 7]]

Vertically stacked (vstack):
 [[89  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]

Horizontally stacked (hstack):
 [[89  1  4  5]
 [ 2  3  6  7]]


## NumPy Array Splitting

In [13]:
# Create an array for splitting with 89 as the first element
arr_split = np.array([89, 10, 20, 30, 40, 50, 60, 70])
print("Original array for splitting:", arr_split)

# Split the array into 4 equal parts
split_arrs = np.split(arr_split, 4)
print("\nSplit into 4 equal parts:", split_arrs)

# Split at specific positions
split_at_pos = np.split(arr_split, [2, 5]) # Split before index 2 and before index 5
print("\nSplit at positions [2, 5]:", split_at_pos)

# Example with 2D array and vsplit/hsplit
arr_2d_split = np.array([[89, 1, 2, 3],
                         [4, 5, 6, 7],
                         [8, 9, 10, 11],
                         [12, 13, 14, 15]])
print("\nOriginal 2D array for splitting:\n", arr_2d_split)

# Vertical split (vsplit) into 2 equal parts
v_split_arrs = np.vsplit(arr_2d_split, 2)
print("\nVertical split (vsplit) into 2 parts:\n", v_split_arrs)

# Horizontal split (hsplit) into 2 equal parts
h_split_arrs = np.hsplit(arr_2d_split, 2)
print("\nHorizontal split (hsplit) into 2 parts:\n", h_split_arrs)

Original array for splitting: [89 10 20 30 40 50 60 70]

Split into 4 equal parts: [array([89, 10]), array([20, 30]), array([40, 50]), array([60, 70])]

Split at positions [2, 5]: [array([89, 10]), array([20, 30, 40]), array([50, 60, 70])]

Original 2D array for splitting:
 [[89  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Vertical split (vsplit) into 2 parts:
 [array([[89,  1,  2,  3],
       [ 4,  5,  6,  7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]

Horizontal split (hsplit) into 2 parts:
 [array([[89,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


## NumPy Universal Functions (Ufuncs)

In [14]:
# Create an array for ufunc demonstration with 89 as the first element
arr_ufunc = np.array([89, 4, 9, 16, 25])
print("Original array for ufuncs:", arr_ufunc)

# Apply np.sqrt ufunc
sqrt_arr = np.sqrt(arr_ufunc)
print("\nSquare root using np.sqrt:", sqrt_arr)

# Apply np.add ufunc (element-wise addition)
arr_add = np.add(arr_ufunc, 10)
print("\nAdd 10 to each element using np.add:", arr_add)

# Apply np.power ufunc
power_arr = np.power(arr_ufunc, 2)
print("\nSquare each element using np.power:", power_arr)

Original array for ufuncs: [89  4  9 16 25]

Square root using np.sqrt: [9.43398113 2.         3.         4.         5.        ]

Add 10 to each element using np.add: [99 14 19 26 35]

Square each element using np.power: [7921   16   81  256  625]


## NumPy Mathematical Methods

In [15]:
# Create an array for mathematical methods demonstration with 89 as the first element
arr_math = np.array([89, 1, 2, 3, 4, 5])
print("Original array for mathematical methods:", arr_math)

# Sum of all elements
print("\nSum of elements:", arr_math.sum())

# Mean of elements
print("Mean of elements:", arr_math.mean())

# Maximum element
print("Maximum element:", arr_math.max())

# Minimum element
print("Minimum element:", arr_math.min())

# Standard deviation
print("Standard deviation of elements:", arr_math.std())

# Product of elements
print("Product of elements:", arr_math.prod())

Original array for mathematical methods: [89  1  2  3  4  5]

Sum of elements: 104
Mean of elements: 17.333333333333332
Maximum element: 89
Minimum element: 1
Standard deviation of elements: 32.076297929918425
Product of elements: 10680
