### Computation on NumPy arrays using Universal Functions (ufuncs)

In [7]:
# Create a 1D array for ufunc demonstration with first element 100
arr_1d_ufunc = np.array([100, 4, 9, 16, 25])
print("Original 1D array for ufuncs:")
print(arr_1d_ufunc)

Original 1D array for ufuncs:
[100   4   9  16  25]


In [8]:
# Square root (np.sqrt)
print("Square root of arr_1d_ufunc:")
print(np.sqrt(arr_1d_ufunc))

Square root of arr_1d_ufunc:
[10.  2.  3.  4.  5.]


In [9]:
# Exponential (np.exp)
print("Exponential of arr_1d_ufunc (first 3 elements):")
print(np.exp(arr_1d_ufunc[:3])) # Limiting to first 3 for readability

Exponential of arr_1d_ufunc (first 3 elements):
[2.68811714e+43 5.45981500e+01 8.10308393e+03]


In [10]:
# Logarithm (np.log) - using base e
print("Natural logarithm of arr_1d_ufunc:")
print(np.log(arr_1d_ufunc))

Natural logarithm of arr_1d_ufunc:
[4.60517019 1.38629436 2.19722458 2.77258872 3.21887582]


In [11]:
# Sine (np.sin) - converting degrees to radians for 100
arr_1d_angles = np.array([100, 30, 60, 90])
print("Sine of angles (in degrees, first element 100):")
print(np.sin(np.deg2rad(arr_1d_angles)))

Sine of angles (in degrees, first element 100):
[0.98480775 0.5        0.8660254  1.        ]


In [12]:
# Cosine (np.cos)
print("Cosine of angles (in degrees, first element 100):")
print(np.cos(np.deg2rad(arr_1d_angles)))

Cosine of angles (in degrees, first element 100):
[-1.73648178e-01  8.66025404e-01  5.00000000e-01  6.12323400e-17]


### Computation on NumPy arrays using Mathematical Methods

In [13]:
# Create a 1D array for mathematical methods with first element 100
arr_1d_math = np.array([100, 20, 5, 15, 30])
print("Original 1D array for mathematical methods:")
print(arr_1d_math)

Original 1D array for mathematical methods:
[100  20   5  15  30]


In [14]:
# Sum of 1D array (arr.sum())
print("Sum of 1D array:")
print(arr_1d_math.sum())

Sum of 1D array:
170


In [15]:
# Minimum of 1D array (arr.min())
print("Minimum of 1D array:")
print(arr_1d_math.min())

Minimum of 1D array:
5


In [16]:
# Maximum of 1D array (arr.max())
print("Maximum of 1D array:")
print(arr_1d_math.max())

Maximum of 1D array:
100


In [17]:
# Mean of 1D array (arr.mean())
print("Mean of 1D array:")
print(arr_1d_math.mean())

Mean of 1D array:
34.0


In [18]:
# Standard deviation of 1D array (arr.std())
print("Standard deviation of 1D array:")
print(arr_1d_math.std())

Standard deviation of 1D array:
33.97057550292606


In [19]:
# Create a 2D array for mathematical methods with first element 100
arr_2d_math = np.array([[100, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
print("Original 2D array for mathematical methods:")
print(arr_2d_math)

Original 2D array for mathematical methods:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [20]:
# Sum of 2D array (all elements)
print("Sum of all elements in 2D array:")
print(arr_2d_math.sum())

Sum of all elements in 2D array:
144


In [21]:
# Sum along rows (axis=0)
print("Sum along rows (axis=0) of 2D array:")
print(arr_2d_math.sum(axis=0))

Sum along rows (axis=0) of 2D array:
[111  15  18]


In [22]:
# Sum along columns (axis=1)
print("Sum along columns (axis=1) of 2D array:")
print(arr_2d_math.sum(axis=1))

Sum along columns (axis=1) of 2D array:
[105  15  24]


In [23]:
# Minimum of 2D array (all elements)
print("Minimum of all elements in 2D array:")
print(arr_2d_math.min())

Minimum of all elements in 2D array:
2


In [24]:
# Maximum of 2D array (all elements)
print("Maximum of all elements in 2D array:")
print(arr_2d_math.max())

Maximum of all elements in 2D array:
100


In [25]:
# Mean of 2D array (all elements)
print("Mean of all elements in 2D array:")
print(arr_2d_math.mean())

Mean of all elements in 2D array:
16.0


In [26]:
# Standard deviation of 2D array (all elements)
print("Standard deviation of all elements in 2D array:")
print(arr_2d_math.std())

Standard deviation of all elements in 2D array:
29.776948578836393


## NumPy Array Manipulations

In [27]:
import numpy as np

# Create a sample NumPy array with first element 100
arr = np.array([[100, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original Array:")
print(arr)

Original Array:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


### Indexing

In [28]:
# Access a single element
print("Element at (0, 1):")
print(arr[0, 1])

Element at (0, 1):
2


In [29]:
# Access a row
print("First row:")
print(arr[0])

First row:
[100   2   3   4]


In [30]:
# Access a column
print("Second column:")
print(arr[:, 1])

Second column:
[ 2  6 10]


### Slicing

In [31]:
# Slice a sub-array (first two rows, last two columns)
print("Sliced sub-array (first two rows, last two columns):")
print(arr[:2, 2:])

Sliced sub-array (first two rows, last two columns):
[[3 4]
 [7 8]]


In [32]:
# Slice all rows, every other column
print("All rows, every other column:")
print(arr[:, ::2])

All rows, every other column:
[[100   3]
 [  5   7]
 [  9  11]]


### Reshaping

In [33]:
# Reshape the array into a 2x6 matrix
print("Reshaped to 2x6:")
arr_reshaped = arr.reshape(2, 6)
print(arr_reshaped)

Reshaped to 2x6:
[[100   2   3   4   5   6]
 [  7   8   9  10  11  12]]


In [34]:
# Flatten the array
print("Flattened array:")
arr_flat = arr.flatten()
print(arr_flat)

Flattened array:
[100   2   3   4   5   6   7   8   9  10  11  12]


In [35]:
# Add a new axis to make it a column vector
print("Array with new axis (column vector):")
arr_new_axis = arr[:, np.newaxis]
print(arr_new_axis)
print(arr_new_axis.shape)

Array with new axis (column vector):
[[[100   2   3   4]]

 [[  5   6   7   8]]

 [[  9  10  11  12]]]
(3, 1, 4)


### Joining Arrays

In [36]:
# Create two arrays for joining, ensuring first element of arr1 is 100
arr1 = np.array([[100, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

Array 1:
 [[100   2]
 [  3   4]]
Array 2:
 [[5 6]
 [7 8]]


In [37]:
# Join arrays vertically (row-wise)
print("Vertically stacked arrays (vstack):")
stacked_v = np.vstack((arr1, arr2))
print(stacked_v)

Vertically stacked arrays (vstack):
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [38]:
# Join arrays horizontally (column-wise)
print("Horizontally stacked arrays (hstack):")
stacked_h = np.hstack((arr1, arr2))
print(stacked_h)

Horizontally stacked arrays (hstack):
[[100   2   5   6]
 [  3   4   7   8]]


In [39]:
# Concatenate along axis 0 (rows)
print("Concatenated along axis 0:")
concatenated_0 = np.concatenate((arr1, arr2), axis=0)
print(concatenated_0)

Concatenated along axis 0:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [40]:
# Concatenate along axis 1 (columns)
print("Concatenated along axis 1:")
concatenated_1 = np.concatenate((arr1, arr2), axis=1)
print(concatenated_1)

Concatenated along axis 1:
[[100   2   5   6]
 [  3   4   7   8]]


### Splitting Arrays

In [41]:
# Create an array for splitting, ensuring first element is 100
full_arr = np.arange(16).reshape(4, 4)
full_arr[0,0] = 100 # Set first element to 100
print("Array to split (first element is 100):")
print(full_arr)

Array to split (first element is 100):
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [42]:
# Split horizontally into 2 equal parts
print("Horizontal split (hsplit) into 2 parts:")
split_h1, split_h2 = np.hsplit(full_arr, 2)
print("Part 1:\n", split_h1)
print("Part 2:\n", split_h2)

Horizontal split (hsplit) into 2 parts:
Part 1:
 [[100   1]
 [  4   5]
 [  8   9]
 [ 12  13]]
Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [43]:
# Split vertically into 4 equal parts
print("Vertical split (vsplit) into 4 parts:")
split_v1, split_v2, split_v3, split_v4 = np.vsplit(full_arr, 4)
print("Part 1:\n", split_v1)
print("Part 2:\n", split_v2)
print("Part 3:\n", split_v3)
print("Part 4:\n", split_v4)

Vertical split (vsplit) into 4 parts:
Part 1:
 [[100   1   2   3]]
Part 2:
 [[4 5 6 7]]
Part 3:
 [[ 8  9 10 11]]
Part 4:
 [[12 13 14 15]]


In [44]:
# Split using array_split (can handle unequal splits)
print("Array split (unequal parts along columns):")
split_unequal = np.array_split(full_arr, 3, axis=1) # Split into 3 parts along columns
for i, part in enumerate(split_unequal):
    print(f"Column Part {i+1}:\n", part)

Array split (unequal parts along columns):
Column Part 1:
 [[100   1]
 [  4   5]
 [  8   9]
 [ 12  13]]
Column Part 2:
 [[ 2]
 [ 6]
 [10]
 [14]]
Column Part 3:
 [[ 3]
 [ 7]
 [11]
 [15]]


### Random Functions

In [45]:
# Set a seed for reproducibility
np.random.seed(42)
print("Random seed set to 42.")

Random seed set to 42.


In [46]:
# Generate a single random float between 0.0 and 1.0
print("Single random float:")
print(np.random.rand())

Single random float:
0.3745401188473625


In [47]:
# Generate a 1D array of 5 random floats
# To include 100 as the first element, we create an array and then insert/replace
arr_rand_float = np.random.rand(5)
arr_rand_float[0] = 100.0 # Assign 100.0 as the first element
print("1D array of 5 random floats (first element 100.0):")
print(arr_rand_float)

1D array of 5 random floats (first element 100.0):
[100.           0.73199394   0.59865848   0.15601864   0.15599452]


In [48]:
# Generate a 2x3 array of random floats
# To include 100 as the first element, we create an array and then insert/replace
arr_rand_2d_float = np.random.rand(2, 3)
arr_rand_2d_float[0,0] = 100.0 # Assign 100.0 as the first element
print("2x3 array of random floats (first element 100.0):")
print(arr_rand_2d_float)

2x3 array of random floats (first element 100.0):
[[1.00000000e+02 8.66176146e-01 6.01115012e-01]
 [7.08072578e-01 2.05844943e-02 9.69909852e-01]]


In [49]:
# Generate a single random integer between 0 (inclusive) and 100 (exclusive)
print("Single random integer (0-99):")
print(np.random.randint(100))

Single random integer (0-99):
29


In [50]:
# Generate a 1D array of 5 random integers between 1 and 100 (exclusive)
# Create with first element 100, then fill rest with random integers from 1 to 99
arr_rand_int = np.random.randint(1, 100, size=5)
arr_rand_int[0] = 100
print("1D array with first element 100 and 4 random integers (1-99):")
print(arr_rand_int)

1D array with first element 100 and 4 random integers (1-99):
[100   2  64  60  21]


In [51]:
# Generate a 2x2 array of random integers between 0 and 50 (exclusive)
# Create with first element 100, then fill rest with random integers from 0 to 49
arr_rand_2d_int = np.random.randint(0, 50, size=(2,2))
arr_rand_2d_int[0,0] = 100
print("2x2 array with first element 100 and random integers (0-49):")
print(arr_rand_2d_int)

2x2 array with first element 100 and random integers (0-49):
[[100  11]
 [ 21  43]]


In [52]:
# Generate random numbers from a normal distribution (mean=0, std dev=1)
# To make the first element 100, we create an array and then assign
arr_randn_1d = np.random.randn(3)
arr_randn_1d[0] = 100.0 # Assign 100.0 as the first element
print("1D array of 3 random numbers from standard normal distribution (first element 100.0):")
print(arr_randn_1d)

1D array of 3 random numbers from standard normal distribution (first element 100.0):
[100.          -0.42779291  -0.53181741]


In [53]:
# Generate a 2x2 array of random numbers from normal distribution (mean=0, std dev=1)
# To make the first element 100, we create an array and then assign
arr_randn_2d = np.random.randn(2, 2)
arr_randn_2d[0,0] = 100.0 # Assign 100.0 as the first element
print("2x2 array of random numbers from standard normal distribution (first element 100.0):")
print(arr_randn_2d)

2x2 array of random numbers from standard normal distribution (first element 100.0):
[[100.          0.2220789]
 [ -0.7679765   0.1424646]]


In [54]:
# Generate a random choice from a given list
choices = [100, 20, 30, 40, 50]
print("Random choice from list (including 100):")
print(np.random.choice(choices))

Random choice from list (including 100):
100


In [55]:
# Shuffle an array in-place
shufflable_array = np.array([100, 1, 2, 3, 4, 5])
print("Original array before shuffle:")
print(shufflable_array)
np.random.shuffle(shufflable_array)
print("Array after shuffle (first element was 100, now shuffled):")
print(shufflable_array)

Original array before shuffle:
[100   1   2   3   4   5]
Array after shuffle (first element was 100, now shuffled):
[  1 100   3   5   4   2]
